// <auto-generated />
namespace FoodApp.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class tableAdd : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(tableAdd));
        
        string IMigrationMetadata.Id
        {
            get { return "202201032356484_tableAdd"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
